### PR TITLE
Adds a basic test for EVMC_INVALID_MEMORY_ACCESS

### PR DESCRIPTION
**Pull request by lrettig**
Issue caught in https://github.com/ewasm/tests/pull/52, waiting for fix in https://github.com/ethereum/cpp-ethereum/pull/5142. Still need to test against updated aleth with this merged. Also still need to fill the test and maybe fix gas.

### CODE REVIEW

**Comment by axic** [comment]
@lrettig I think this can be merged since aleth was fixed?

**Comment by lrettig** [comment]
Good to go, @hugo-dc could you take a look? Thanks!

**Review by hugo-dc — APPROVED** [review]
LGTM!

**Comment by lrettig** [comment]
Thanks Hugo

**Pull request merged**
