### PR TITLE
Remove debug imports and debug calls from test cases

### PR DESCRIPTION
**Pull request by hugo-dc**
Remove debug imports and statements from test cases as this causes problems with running with hera when hera is build using the -DHERA_DEBUGGING=OFF flag.

### CODE REVIEW

**Comment by chfast** [comment]
Is this ready?

**Review by chfast — APPROVED** [review]

**Comment by chfast** [comment]
Testing: https://circleci.com/workflow-run/99d916f0-3c83-43e9-9289-c7524d833c7f

**Comment by chfast** [comment]
There is one error
```
/home/builder/project/test/tools/libtesteth/TestSuite.cpp(98): error: in "GeneralStateTests/stEWASMTests": Test tests/GeneralStateTests/stEWASMTests/getBalanceExt.json in getBalanceExt is outdated. Filler hash is different!
```

**Comment by hugo-dc** [comment]
@chfast error should be fixed now, I added the filled file for getBalanceExt

**Comment by chfast** [comment]
Testing: https://circleci.com/workflow-run/18549832-f993-4ef4-8b93-90e0f4bf4b58

**Comment by chfast** [comment]
:+1:

**Review by jwasinger — APPROVED** [review]
LGTM

**Pull request merged**
