### PR TITLE
Add a more comprehensive CREATE test

### PR DESCRIPTION
**Pull request by lrettig**
Child of #39

### CODE REVIEW

**Comment by lrettig** [comment]
@hugo-dc could you please have a look at this new test? Thanks!

**Review by hugo-dc — APPROVED** [review]
The test looks great, tested with latest hera and it is working correctly, but cpp-ethereum asked me to refill the test again, see comment below

**Review by hugo-dc — CHANGES_REQUESTED** [review]
cpp-ethereum showed me an error indicating the test is not filled correctly:
Test  in createNonzero is outdated. Filler hash is different! 
After I refilled the test it worked as expected, please fill the test again

**Comment by lrettig** [comment]
Strange, that's the second time that's happened. I wonder what causes that to happen. Thanks for taking a look Hugo, I'll update and merge.

**Pull request merged**
