### PR TITLE
Test malformed imports - Part 1

### PR DESCRIPTION
**Pull request by hugo-dc**
This PR contains the following test cases for malformed imports:

- [X] malformedImportCallCodeFourParams
- [X] malformedImportCallCodeOneParam
- [X] malformedImportCallCodeThreeParams
- [X] malformedImportCallCodeTwoParams
- [X] malformedImportCallCodeZeroParams
- [X] malformedImportCallDataCopyOneParam
- [X] malformedImportCallDataCopyTwoParams
- [X] malformedImportCallDataCopyZeroParams
- [X] malformedImportCallDataSizeOneParamNoReturn
- [X] malformedImportCallDataSizeOneParamWithReturn
- [X] malformedImportCallDelegateFiveParams
- [X] malformedImportCallDelegateOneParam
- [X] malformedImportCallDelegateThreeParams
- [X] malformedImportCallDelegateTwoParams
- [X] malformedImportCallDelegateZeroParams
- [X] malformedImportCallFourParams
- [X] malformedImportCallOneParam
- [X] malformedImportCallStaticFiveParams
- [X] malformedImportCallStaticOneParam
- [X] malformedImportCallStaticThreeParams
- [X] malformedImportCallStaticTwoParams
- [X] malformedImportCallStaticZeroParams
- [X] malformedImportCallThreeParams
- [X] malformedImportCallTwoParams
- [X] malformedImportCallZeroParams

### CODE REVIEW

**Review by jakelang — DISMISSED** [review]
lgtm

**Comment by axic** [comment]
All these malformed ones should be refilled after https://github.com/ewasm/hera/pull/448.

**Comment by lrettig** [comment]
@axic commented that malformed code cannot make it into the state and therefore hera is not prepared to handle these. Also, these are all failing for me right now against hera master (0fc33efc73db7d0f9a4b2b32a7ecd9cb5b26258e) as gas calcs appear to be off. @hugo-dc let's discuss when you're online.

**Comment by axic** [comment]
@hugo-dc all these testes need to be refilled with Hera 0.2.0.

**Comment by hugo-dc** [comment]
Refilled tests with hera 0.2.0, fixed used gas, now is consuming all tx gas due to malformed import exceptions/errors.

**Review by axic — APPROVED** [review]

**Pull request merged**
