### PR TITLE
Run travis on wasm-tests branch too

### LINKED ISSUE #25: Should run the schema validation on stEWASM
See https://github.com/ethereum/tests/tree/develop/JSONSchema

### PR DESCRIPTION
**Pull request by axic**
Fixes #25.

### CODE REVIEW

**Comment by axic** [comment]
This has found the following issues:
```
== test.py: ERROR: Filler hash is different: ./GeneralStateTests/stEWASMTests/callSenderBalanceExceeds128Bits.json
== test.py: ERROR: Filler hash is different: ./GeneralStateTests/stEWASMTests/callValue.json
== test.py: ERROR: Filler hash is different: ./GeneralStateTests/stEWASMTests/callValueExceeds64bit.json
== test.py: ERROR: Filler hash is different: ./GeneralStateTests/stEWASMTests/callValueExceedsBalance.json
```

@hugo-dc @jwasinger @lrettig can you check?

**Comment by hugo-dc** [comment]
@axic I had the same problem when creating EXTCODEHASH tests for the main tests repo, @winsvega pointed out that the balance values has to be quoted, I created a PR quoting the balance values and refilling the tests: https://github.com/ewasm/tests/pull/109

I didn't fix this test case yet: `callSenderBalanceExceeds128Bits`, I don't know which hera branch/version @gballet used to fill the test, in hera `0.2.0` it is failing.

**Comment by winsvega** [comment]
You mean its failing the json scheme check?

Or failing to generate the correct post state?

**Comment by axic** [comment]
@hugo-dc the PR was #105 and it isn't 0.2.0 for that test case, but Hera master, because it was fixed after 0.2.0. Will release 0.2.1 soon, but you can just use master now.

**Comment by axic** [comment]
After merging your PR these are two failing ones:
```
== test.py: ERROR: Filler hash is different: ./GeneralStateTests/stEWASMTests/callSenderBalanceExceeds128Bits.json
== test.py: ERROR: Filler hash is different: ./GeneralStateTests/stEWASMTests/callValueExceedsBalance.json
```

**Comment by axic** [comment]
> You mean its failing the json scheme check?

@winsvega we haven't had the scheme checks enabled and as a result some files are inconsistent.

**Comment by axic** [comment]
@hugo-dc released Hera 0.2.1, you can use that to fill the 128-bit tests.

**Comment by winsvega** [comment]
If you run testeth with ewasm tests enabled, it should detect testerrors and perform test check. The python script in travis just double check that

**Comment by winsvega** [comment]
Filler hash is different means that test source was changed and the test needs to be refilled

**Comment by hugo-dc** [comment]
> Filler hash is different means that test source was changed and the test needs to be refilled

Yes, and you also pointed out [here](https://github.com/ethereum/tests/pull/542#issuecomment-437330764) that the hash validation may fail if the values in the yaml files are not properly quoted (defined as string or int correctly).

**Comment by hugo-dc** [comment]
@axic tests were refilled here: https://github.com/ewasm/tests/pull/111

**Comment by axic** [comment]
It fails with something new:
```
TypeError: '<' not supported between instances of 'int' and 'str'
```

**Comment by winsvega** [comment]
Yes, and you also pointed out here that the hash validation may fail if the values in the yaml files are not properly quoted (defined as string or int correctly)

Yes, but thats true only for python script

**Comment by axic** [comment]
@winsvega I actually like the strictness of the python script

**Comment by axic** [comment]
@hugo-dc it seems there are couple of hash mismatches. Can you run the python script locally (it doesn't work here on the mac) ?

I think this is the final list though, previously it failed due to that key comparison issue:
```
[ERROR] Filler hash is different: ./GeneralStateTests/stEWASMTests/initMalformedBytecodeNoMainFromTx.json
[ERROR] Filler hash is different: ./GeneralStateTests/stEWASMTests/validateBytecodeInvalidNamespaceFromTxIsInvalid.json
[ERROR] Filler hash is different: ./GeneralStateTests/stEWASMTests/initMalformedBytecodeMissingMemoryExportFromTx.json
[ERROR] Filler hash is different: ./GeneralStateTests/stEWASMTests/validateBytecodeMissingVersionOneByteFromTxIsInvalid.json
[ERROR] Filler hash is different: ./GeneralStateTests/stEWASMTests/initMalformedBytecodeHasStartFromTx.json
[ERROR] Filler hash is different: ./GeneralStateTests/stEWASMTests/validateBytecodeBadVersionFromTxIsInvalid.json
[ERROR] Filler hash is different: ./GeneralStateTests/stEWASMTests/validateBytecodeMissingVersionFromTxIsInvalid.json
[ERROR] Filler hash is different: ./GeneralStateTests/stEWASMTests/validateBytecodeInvalidImportFromTxIsInvalid.json
[ERROR] Filler hash is different: ./GeneralStateTests/stEWASMTests/validateBytecodeMissingVersionTwoBytesFromTxIsInvalid.json
[ERROR] Filler hash is different: ./GeneralStateTests/stEWASMTests/initMalformedBytecodeInvalidMainFromTx.json
[ERROR] Filler hash is different: ./GeneralStateTests/stEWASMTests/validateBytecodeEmptyInitFromTxIsInvalid.json
```

**Comment by hugo-dc** [comment]
@axic  created a PR to fix the remaining hash issues: https://github.com/ewasm/tests/pull/113

**Comment by axic** [comment]
Thanks @hugo-dc, this works now finally!

**Comment by winsvega** [comment]
the striktness is the same, it is just that testeth convert yaml to json first then perform the check.

**Comment by winsvega** [comment]
how did you fix 
`TypeError: '<' not supported between instances of 'str' and 'int'`
?

**Comment by axic** [comment]
Some of the contracts for the expected storage had a `0x` prefix. See #112.

**Comment by winsvega** [comment]
looks like this issue also happen when you just name contracts as `10000...000`  it is considerate to be int. 
so to fix this such accounts must be quoted with single quote

**Pull request merged**
