### PR TITLE
Adds out-of-bounds memory test cases

### LINKED ISSUE #34: OOB memory access test cases
As we are deviating from EVM1 with regards to how the EEI treats reads from OOB memory (see https://github.com/ewasm/hera/pull/222), we need test cases that capture this spec change.

`externalCodeCopy`, `codeCopy` and `returnDataCopy` need to have test cases to make sure that: copying from OOB memory traps.

Cf: https://github.com/ewasm/evm2wasm/issues/250

### PR DESCRIPTION
**Pull request by lrettig**
Closes #34
~Requires https://github.com/ewasm/hera/pull/256~
Requires https://github.com/ewasm/hera/pull/272

- [x] codeCopyOOB
- [x] extCodeCopyOOB
- [x] returnDataCopy (https://github.com/ewasm/tests/pull/54)
- [x] returnDataCopyOOB

### CODE REVIEW

**Comment by lrettig** [comment]
For some reason I'm getting an uncaught exception when I try to run/fill the `returnDataCopyOOB` test:

```
> cpp-ethereum/build/test/testeth -t GeneralStateTests/stEWASMTests -- --testpath ~/eth/tests/ --singlenet Byzantium --singletest returnDataCopyOOB --jsontrace '' --vm ~/eth/hera2/build/src/libhera.dylib --filltests
Running tests using path: "~/eth/tests/"
Running 1 test case...
Test Case "stEWASMTests":
100%
Executing...
importGlobals
$call 186a0 220 0 0 0
Executing...
importGlobals
$call 186a0 200 0 0 0
getReturnDataSize
returnDataCopy 400 0 1
Out of bounds (source) memory copy.
libc++abi.dylib: terminating with uncaught exception of type boost::exception_detail::clone_impl<dev::eth::InternalVMError>: ~/eth/cpp-ethereum/libevm/EVMC.cpp(76): Throw in function virtual dev::eth::owning_bytes_ref dev::eth::EVMC::exec(dev::u256 &, dev::eth::ExtVMFace &, const dev::eth::OnOpFunc &)
Dynamic exception type: boost::exception_detail::clone_impl<dev::eth::InternalVMError>
[dev::eth::tag_evmcStatusCode*] = 9

unknown location:0: fatal error: in "GeneralStateTests/stEWASMTests": signal: SIGABRT (application abort requested)
~/eth/cpp-ethereum/test/tools/libtesteth/wast2wasm.cpp:41: last checkpoint

*** 1 failure is detected (5 failures are expected) in the test module "Master Test Suite"
```

**Comment by lrettig** [comment]
@axic @chfast would appreciate your feedback on the above error, I'm kinda stumped. It's happening in this test when I make a transaction to contract A, which CALLs contract B, which calls `returnDataCopy` out of bounds which traps.

**Comment by axic** [comment]
I'm not sure what the problem is? The error code seems to be correct, `9` equals to `EVMC_INVALID_MEMORY_ACCESS` which corresponds to the message displayed?

**Comment by lrettig** [comment]
@axic two things:

1. If this same error occurs in contract A rather than contract B, it's caught gracefully in Hera [here](https://github.com/ewasm/hera/blob/32ff0f6ade3b86a4b933307fb3bd6da7e78eb9e6/src/hera.cpp#L438) -- why isn't this being caught by Hera?

2. What's the expected behavior if contract A calls contract B and contract B traps? Shouldn't execution return to contract A and the `call` return fail? Rather than bailing out completely.

**Comment by axic** [comment]
> What's the expected behavior if contract A calls contract B and contract B traps? Shouldn't execution return to contract A and the call return fail? Rather than bailing out completely.

Correct. This seems to be a bug in cpp-ethereum.

**Comment by axic** [comment]
This here https://github.com/ethereum/cpp-ethereum/blob/develop/libevm/EVMC.cpp#L77 doesn't handle `EVMC_INVALID_MEMORY_ACCESS`.

Why is `InternalVMError` here considered as fatal?

@chfast @gumb0 what is the best way forward?

**Comment by axic** [comment]
Hopefully fix is here: https://github.com/ethereum/cpp-ethereum/pull/5142

**Comment by chfast** [comment]
> Why is InternalVMError here considered as fatal?

1. The error handling is common for testing and for the Client. The Client has not better option just to exit.
2. To detect issues in the VM (like here).

**Comment by lrettig** [comment]
This is ready for review, @hugo-dc would you do the honors?

Note that this depends on ewasm/hera#272 which isn't merged yet

**Review by hugo-dc — COMMENTED** [review]
Tested with latest aleth/hera, all tests looks great, currently I'm getting post state hash errors, but seems it is because the json files needs to be refilled, after the tests are refilled all test cases work as expected. Please take a look and refill the tests if needed. Thanks!

**Comment by lrettig** [comment]
Will do gracias amigo!

**Pull request merged**
