### PR TITLE
Add tests for malformed init code (2)

### PR DESCRIPTION
**Pull request by lrettig**
Forked from #92, these tests are failing pending ewasm/hera#441 and ewasm/hera#442 (nb. https://github.com/ewasm/tests/pull/92#issuecomment-428036721).

### CODE REVIEW

**Comment by lrettig** [comment]
Rebased and refilled. These are passing now against hera `master` since https://github.com/ewasm/tests/pull/96 was fixed.

**Comment by axic** [comment]
Depends on https://github.com/ewasm/hera/pull/448 I think.

**Comment by axic** [comment]
Also can you please rebase?

**Comment by lrettig** [comment]
@axic just rebased against the latest `wasm-tests` branch and I've confirmed that the tests pass against the current hera master. Looks good to go to me.

**Review by axic — APPROVED** [review]

**Pull request merged**
