### PR TITLE
Add document to track and describe EWASM Test Cases

### PR DESCRIPTION
**Pull request by jwasinger**
I went through existing test cases, both on https://github.com/ewasm/tests/tree/wasm-tests and https://github.com/lrettig/tests/tree/wasm-tests (which will soon be merged).

I put together a document describing these test cases that we can use to track test coverage as we write new cases.

### CODE REVIEW

**Comment by lrettig** [comment]
Some of my test fillers contain tests for multiple operations. Would you like me to update this doc with these? I saw that some of them haven't been filled in here

**Comment by jwasinger** [comment]
Yeah sure

**Comment by axic** [comment]
@jwasinger @lrettig is this PR still relevant?

**Comment by lrettig** [comment]
The doc exists here: https://notes.ethereum.org/9xX4L2QyQPmzJ0Xh3RAgJA. I've been keeping it reasonably up to date. This PR is relevant if we want a canonical version of it in the tests repo as well.

**Comment by axic** [comment]
Can we have one canonical version?

**Comment by lrettig** [comment]
If it would require a PR every time it changed, then just close this and leave it in hackmd for now.

**Comment by axic** [comment]
Suggests closing this then.

**Comment by jwasinger** [comment]
HackMD works fine for this.  Having to include test descriptions in the repo could be a bit clunky.

**Pull request closed without merging**
