### PR TITLE
Remove duplicate test for getGasLeft

### PR DESCRIPTION
**Pull request by lrettig**
There were two versions of this test, removed getGasLeftConsumeAllGas
since it never even calls getGasLeft. getGasLeftUseAllGas does.

### CODE REVIEW

**Review by hugo-dc — APPROVED** [review]
Agree, this should be removed as it is already tested in other test case

**Comment by axic** [comment]
To me it seems this test indeed called `getGasLeft`. Are you sure the correct one was removed?

**Comment by lrettig** [comment]
There were two nearly identical tests, `getGasLeftConsumeAllGas` and `getGasLeftUseAllGas`. I deleted the former.

**Comment by axic** [comment]
The description above says:

> removed getGasLeftConsumeAllGas since it never even calls getGasLeft.

**Comment by lrettig** [comment]
Ah. It didn't actually call `getGasLeft` because it actually ran out of gas first. The remaining test does.

**Pull request merged**
