### PR TITLE
Make sure selfDestruct test expects destroyed account to not exist at the end of the transaction

### PR DESCRIPTION
**Pull request by jwasinger**

### CODE REVIEW

**Comment by hugo-dc** [comment]
This change looks good, but I have some questions related to this test case. 

At the beginning both accounts has a balance of 100000000000, so when the second account destruct itself the total balance should be passed to the caller, I would expect 200000000000 in the first account or 200000000000 - 21000 (Tx cost) = 199999979000, but instead we are getting 199999989500 (200000000000 - 10500), I'm not sure what those 10500 means and if it is ok to not reduce the transaction cost, also I see that in the post state we have a new account:

https://github.com/ewasm/tests/blob/self-destruct/GeneralStateTests/stEWASMTests/selfDestruct.json#L29-L34

And by the way the balance of that new account is 10500.

**Review by lrettig — COMMENTED** [review]
Change looks good.

Agree with @hugo-dc, I would like to understand the gas semantics here.

One more thing: should we test this behavior of [`selfDestruct`](https://github.com/ewasm/design/blob/master/eth_interface.md#selfdestruct)?

> Note: the contract shall halt execution after this call.

**Comment by jwasinger** [comment]
Yeah @lrettig that is a good idea.  If we could add some code after the selfdestruct  (maybe a call to another account where the executed code causes a state change), that would be great.

**Comment by axic** [comment]
Maybe the gas issues are due to this: https://github.com/ethereum/cpp-ethereum/pull/4731 ?

**Review by hugo-dc — APPROVED** [review]
I think we should merge this change, and document the gas issues in @jwasinger https://github.com/ewasm/tests/pull/7

**Review by lrettig — CHANGES_REQUESTED** [review]
add some code after the selfdestruct (maybe a call to another account where the executed code causes a state change)

**Pull request merged**
